### ISSUE TITLE
Create a "shared link" page.

### ISSUE THREAD

**Issue by lijamie98** [Telenav/dropbox-admin#8]
From menu, create a link to list all "shared links" page. 

The REST api is 
http://localhost:5000/links

The following fields should be listed.
- path of the shared link. (folder)
- url of the shared link.
- link creation date.
- expiration date. Display "not set" if it is not set.

Future
- The user who shares the folder as a link.
- Revoke the link.
- Set expiration date.

**Comment by mashedpotats** [comment]
Finished the required fields. Awaiting more back-end code for the future requirements.
